### ISSUE TITLE
Version number?

### ISSUE THREAD

**Issue by iDGS** [secondparty/arrange#1]
I found this after wondering if there was a more recent version of Arrange than the one I just stumbled upon inside my favorite CMS :-) Indeed, it looks like you've changed indents from 3 to 4 spaces, added a few `margin: 0;`s, and a new `one-ninth` class (did I miss anything?)—so the answer's a definite "yes!"

Thus, given that it's new and improved, I was just curious about why you dropped the version number thing from inside your leading comment? Wouldn't it make sense for this to be `1.3`?

Could be just me, but I find embedded version numbers super-helpful in sorting out whether I'm up to date on this and that. Hope you agree... (?)

In any case, I hope to learn a few things from seeing how you did all this. Thanks for posting this repo!

**Comment by fredleblanc** [comment]
I removed the versions for a couple of reasons, although who knows if any of them are good.
1. I switched the location of the repository to standalone by itself.
2. At this point, the math and styles are solid enough that this technically could be a real v1.0. There shouldn't be anything left to bug fix. 
3. Anything else that changes from here on forward is probably adding things. I added the one-ninth stuff, but that's probably the limit.

I think at this point, tagging the releases makes sense to track any changes. I think that's a good compromise. Then you can check in there for newer releases.

**Comment by iDGS** [comment]
Thanks. It's definitely your call, so I'll be happy to listen. :-)
